name: Trigger Daily Build

on:
  schedule:
    - cron: '*/15 * * * *'  # run every 15 min, but will only push pp1 once daily between 8-9PM

jobs:
  update_md_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit and Push Changes
        run: |
          git config user.name "ECCRedM-Media"
          git config user.email "ECCRedM-Media@gmail.com"    

          # In order to avoid daylight saving error, run this action twice daily but only push once after making sure PST is after 8PM.
          
          current_time=$(TZ="America/Los_Angeles" date "+%H:%M")
          start_time="18:25"
          end_time="19:00"

          if [[ "$current_time" > "$start_time" && "$current_time" < "$end_time" ]]; then
            echo "It's 8:15. Push pp1 to trigger build."
            current_date=$(TZ="America/Los_Angeles" date +"%Y-%m-%d")
            file_content=$(cat pp1)

            if [ "$current_date" != "$file_content" ]; then
               echo "$current_date" > pp1
               git add -A
               git commit -m "Update pp1"  # Use -m to provide a commit message
               git push
            fi
          fi
