name: Trigger Daily Build

on:
  schedule:
    - cron: '30 0 * * *' 

jobs:
  update_md_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit and Push Changes
        run: |
          git config user.name "ECCRedM-Media"
          git config user.email "ECCRedM-Media@gmail.com"    

          current_date=$(TZ="America/Los_Angeles" date +"%Y-%m-%d")
          echo "Push pp1 to trigger build."

          echo "$current_date" > pp1
          git add -A
          git commit -m "Update pp1"  # Use -m to provide a commit message
          git push
