name: Trigger Daily Build

on:
  schedule:
    - cron: '30 22 * * *' 
    - cron: '30 23 * * *' 
    - cron: '30 00 * * *' 

jobs:
  update_md_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit and Push Changes
        run: |
          git config user.name "ECCRedM-Media"
          git config user.email "ECCRedM-Media@gmail.com"    

          current_date=$(TZ="America/Los_Angeles" date +"%Y-%m-%d")
          pp1_content=$(<pp1)
          
          echo "$current_date"
          echo "$pp1_content"
          
          if [ "$current_date" == "$pp1_content" ]; then
            echo "The content of the variable and the file are the same. No action needed."
          else
            echo "Push pp1 to trigger build."
            echo "$current_date" > pp1
            git add -A
            git commit -m "Update pp1"  # Use -m to provide a commit message
            git push
          fi
