name: Trigger Daily Build

on:
  schedule:
    - cron: '15 2 * * *' 
    - cron: '30 2 * * *' 
    - cron: '45 2 * * *' 
    - cron: '15 3 * * *' 
    - cron: '30 3 * * *' 
    - cron: '45 3 * * *' 

jobs:
  update_md_file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Commit and Push Changes
        run: |
          git config user.name "ECCRedM-Media"
          git config user.email "ECCRedM-Media@gmail.com"    

          current_time=$(TZ="America/Los_Angeles" date "+%H:%M")
          start_time="18:05" #try to build between 6-7pm so build will finish before 7pm release
          end_time="21:00"
          echo "$current_date"
          echo "$current_time"
          if [[ "$current_time" > "$start_time" && "$current_time" < "$end_time" ]]; then
            echo "Push pp1 to trigger build."
            current_date=$(TZ="America/Los_Angeles" date +"%Y-%m-%d")
            file_content=$(cat pp1)

            if [ "$current_date" != "$file_content" ]; then
               echo "$current_date" > pp1
               git add -A
               git commit -m "Update pp1"  # Use -m to provide a commit message
               git push
            fi
          fi
